<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<div class="nested0" xml:lang="en-US" id="N20006"><a name="N20006"><!-- --></a><h1 class="topictitle1">About</h1>
<div>
        <p>
            The DITA Open Platform is a free, open-source project which
            goal is to provide an enterprise platform for the edition,
            management and processing of DITA documents.
        </p>

    </div>
<div class="nested1" xml:lang="en-US" id="N70006"><a name="N70006"><!-- --></a><h2 class="topictitle2">License</h2>
<div>
        <p>
            The DITA Open Platform is free software: you can
            redistribute it and/or modify it under the terms of the
            <a href="http://www.gnu.org/licenses/" target="_blank">
                GNU General Public License
            </a>
            as published by the Free Software Foundation, either version
            3 of the License, or (at your option) any later version.
        </p>


        <p>
            The DITA Open Platform is distributed in the hope that it
            will be useful, but WITHOUT ANY WARRANTY; without even the
            implied warranty of MERCHANTABILITY or FITNESS FOR A
            PARTICULAR PURPOSE. See the GNU General Public License for
            more details.
        </p>


        <p>
            A copy of the
            <a href="http://www.gnu.org/licenses/" target="_blank">
                GNU General Public License
            </a>
            is distributed along with The DITA Open Platform.
        </p>

    </div>
</div>
<div class="nested1" xml:lang="en-US" id="N80006"><a name="N80006"><!-- --></a><h2 class="topictitle2">Copyright</h2>
<div>
        <p>
            Unless otherwise specified the DITA Open Platform is
            copyright (C) 2008
            <a href="http://vedovini.net/" target="_blank">
                Claude Vedovini.
            </a>
        </p>

    </div>
</div>
<div class="nested1" xml:lang="en-US" id="N90006"><a name="N90006"><!-- --></a><h2 class="topictitle2">Credits</h2>
<div>
        <div class="p">
            This product includes work produced by the following
            organizations, projects or individuals which is distributed
            under their own copyrights and license terms.
            <br><ul>
                <li>
                    The
                    <a href="http://www.oasis-open.org/committees/dita" target="_blank">
                        OASIS DITA Technical Committee.
                    </a>
                </li>

                <li>
                    The
                    <a href="http://dita-ot.sourceforge.net/" target="_blank">
                        DITA Open Toolkit Project
                    </a>
                    (under the
                    <a href="http://www.opensource.org/licenses/cpl1.0.php" target="_blank">
                        Common Public License
                    </a>
                    ).
                </li>

                <li>
                    <a href="http://www.famfamfam.com/" target="_blank">
                        Mark James
                    </a>
                    (under the
                    <a href="http://creativecommons.org/licenses/by/2.5/" target="_blank">
                        Creative Commons Attribution 2.5 License
                    </a>
                    ).
                </li>

            </ul>

        </div>

    </div>
</div>
</div>
