<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<div class="nested0" xml:lang="en-US" id="N20006"><a name="N20006"><!-- --></a><h1 class="topictitle1">Downloading the DITA-OP Editor</h1>
<div>
        <div class="section">
            To download the DITA-OP Editor plugins you may choose one of
            the following options.
        </div>

    </div>
<div class="nested1" id="N20032"><a name="N20032"><!-- --></a>
        <h2 class="topictitle2">Downloading the full package</h2>

        <div>
            <div class="section">
                <p>
                    This package includes the Eclipse IDE for windows,
                    the DITA-OP plugins (and their dependencies), the
                    CVS plugin and
                    <a href="http://subclipse.tigris.org/" target="_blank">
                        Subclipse, the SVN team plugin.
                    </a>
                </p>

                <p>
                    Work is still needed on this package to remove
                    things that are not becessary to a typical technical
                    writer but it is a good start if you do not use
                    Eclipse already and want to evaluate the editor.
                </p>

                <p>
                    Also, it is only available for windows and if demand
                    is high enough for other platforms we will build
                    other packages. In the mean time, if you are using
                    another platform please
                    <a href="http://www.eclipse.org/downloads/" target="_blank">
                        download the Eclipse IDE for your platform
                    </a>
                    and use one the other download methods.
                </p>

            </div>

            <ol>
                <li>
                    <span>
                        Go to the
                        <a href="http://sourceforge.net/project/showfiles.php?group_id=228491&package_id=276725" target="_blank">
                            project's download page.
                        </a>
                    </span>
                </li>

                <li>
                    <span>
                        Choose the
                        <span class="filepath">
                            doped-1.0.0.M1-20080618-win32.zip
                        </span>
                        zip file.
                    </span>
                </li>

                <li>
                    <span>
                        Unzip the file anywhere on your file system and
                        run the
                        <span class="filepath">eclipse.exe</span>
                        file contained in the newly created
                        <span class="filepath">doped-1.0.0.M1-20080618</span>
                        folder.
                    </span>
                </li>

            </ol>

        </div>

    </div>
<div class="nested1" id="N200B6"><a name="N200B6"><!-- --></a>
        <h2 class="topictitle2">Downloading the plugins zip file</h2>

        <div>
            <div class="section">
                If you are already using Eclipse 3.3 (Europa) you can
                download the plugins zip file.
            </div>

            <ol>
                <li>
                    <span>
                        Go to the
                        <a href="http://sourceforge.net/project/showfiles.php?group_id=228491&package_id=276725" target="_blank">
                            project's download page.
                        </a>
                    </span>
                </li>

                <li>
                    <span>
                        Choose the
                        <span class="filepath">
                            org.dita_op_1.0.0.M1-20080618-bin.zip
                        </span>
                        zip file.
                    </span>
                </li>

                <li>
                    <span>
                        Once downloaded, unzip the file in the Eclipse
                        folder (the one which contains the
                        <span class="filepath">features</span>
                        and
                        <span class="filepath">plugins</span>
                        folders).
                    </span>
                </li>

                <li>
                    <span>If necessary, restart Eclipse.</span>
                </li>

            </ol>

        </div>

    </div>
<div class="nested1" id="N20122"><a name="N20122"><!-- --></a>
        <h2 class="topictitle2">Using the update site</h2>

        <div class="nested2" id="N20130"><a name="N20130"><!-- --></a>
            <h3 class="topictitle3">Eclipse 3.3 (Europa)</h3>

            <div>
                <div class="section">
                    If you are already using Eclipse 3.3 you can use the
                    Update Manager to download and install the plugins
                    for you.
                </div>

                <ol>
                    <li>
                        <span>
                            Open Eclipse, go to
                            <span class="menucascade">
                                <span class="uicontrol">Help</span>
                                 &gt; <span class="uicontrol">Software Updates</span>
                                 &gt; <span class="uicontrol">
                                    Find and Install...
                                </span>
                            </span>
                        </span>
                    </li>

                    <li>
                        <span>
                            Choose
                            <span class="uicontrol">
                                Search for new features to install.
                            </span>
                        </span>
                    </li>

                    <li>
                        <span>
                            Click on the
                            <span class="uicontrol">"New Remote Site..."</span>
                            button.
                        </span>
                    </li>

                    <li>
                        <span>
                            Enter
                            <kbd class="userinput">DITA-OP Update Site</kbd>
                            in the
                            <span class="uicontrol">name</span>
                            field.
                        </span>
                    </li>

                    <li>
                        <span>
                            Enter
                            <kbd class="userinput">
                                http://www.dita-op.org/updatesite
                            </kbd>
                            in the
                            <span class="uicontrol">URL</span>
                            field.
                        </span>
                    </li>

                    <li>
                        <span>
                            Click on the
                            <span class="uicontrol">OK</span>
                            button.
                        </span>
                    </li>

                    <li>
                        <span>
                            Make sure the
                            <span class="uicontrol">DITA-OP Update Site</span>
                            check box is selected (you may have to
                            select the
                            <span class="uicontrol">Europa Discovery Site</span>
                            as well to fetch dependencies).
                        </span>
                    </li>

                    <li>
                        <span>
                            Click on the
                            <span class="uicontrol">Finish</span>
                            button.
                        </span>
                    </li>

                    <li>
                        <span>
                            Select the
                            <span class="uicontrol">DITA-OP Update Site</span>
                            check box (if an error appears about missing
                            dependencies click on the
                            <span class="uicontrol">Select Required</span>
                            button).
                        </span>
                    </li>

                    <li>
                        <span>
                            Click on the
                            <span class="uicontrol">Next</span>
                            button.
                        </span>
                    </li>

                    <li>
                        <span>
                            Choose the
                            <span class="uicontrol">
                                I accept the terms in the license
                                agreement
                            </span>
                            radio button.
                        </span>
                    </li>

                    <li>
                        <span>
                            Click on the
                            <span class="uicontrol">Next</span>
                            button.
                        </span>
                    </li>

                    <li>
                        <span>
                            Click on the
                            <span class="uicontrol">Finish</span>
                            button.
                        </span>
                    </li>

                    <li>
                        <span>Wait for the download to complete.</span>
                    </li>

                    <li>
                        <span>
                            Click on the
                            <span class="uicontrol">Install</span>
                            button.
                        </span>
                    </li>

                    <li>
                        <span>
                            Click on the
                            <span class="uicontrol">Yes</span>
                            button to restart Eclipse.
                        </span>
                    </li>

                </ol>

            </div>

        </div>

        <div class="nested2" id="N20295"><a name="N20295"><!-- --></a>
            <h3 class="topictitle3">Eclipse 3.4 (Ganymede)</h3>

            
            <div>
                <div class="section">
                    Eclipse 3.4 has an updated Update Manager called P2
                    and so the process is slightly different. Thanks to
                    Richard Pineger for the following install
                    instructions.
                </div>

                <ol>
                    <li>
                        <span>
                            Open Eclipse, go to
                            <span class="menucascade">
                                <span class="uicontrol">Help</span>
                                 &gt; <span class="uicontrol">
                                    Software Updates...
                                </span>
                            </span>
                        </span>
                    </li>

                    <li>
                        <span>
                            Select the
                            <span class="uicontrol">Available Software</span>
                            tab.
                        </span>
                    </li>

                    <li>
                        <span>
                            Click
                            <span class="uicontrol">Add Site...</span>
                        </span>
                    </li>

                    <li>
                        <span>
                            In the
                            <span class="uicontrol">Add Site</span>
                            dialog, enter
                            <kbd class="userinput">
                                http://www.dita-op.org/updatesite
                            </kbd>
                            in the
                            <span class="uicontrol">Location</span>
                            field.
                        </span>
                    </li>

                    <li>
                        <span>
                            Click the
                            <span class="uicontrol">OK</span>
                            button.
                        </span>
                    </li>

                    <li>
                        <span>
                            Make sure the
                            <span class="uicontrol">
                                http://www.dita-op.org/updatesite
                            </span>
                            check box and
                            <span class="uicontrol">Uncategorized</span>
                            check boxes are selected.
                        </span>
                    </li>

                    <li>
                        <span>
                            Click the
                            <span class="uicontrol">Install...</span>
                            button.
                        </span>
                    </li>

                    <li>
                        <span>
                            Wait for the Update Manager to resolves
                            dependencies.
                        </span>
                    </li>

                    <li>
                        <span>
                            Read and accept the necessary license
                            agreements.
                        </span>
                    </li>

                    <li>
                        <span>
                            Wait for the download and install to
                            complete.
                        </span>
                    </li>

                    <li>
                        <span>
                            Click on the
                            <span class="uicontrol">Yes</span>
                            button to restart Eclipse.
                        </span>
                    </li>

                </ol>

            </div>

        </div>

    </div>
<div class="nested1" id="N20395"><a name="N20395"><!-- --></a>
        <h2 class="topictitle2">Nightly builds</h2>

        <div>
            <div class="section">
                Nightly builds are available at
                <a href="http://www.pluginbuilder.org" target="_blank">
                    pluginbuilder.org
                </a>
                you can either download the latest plugins zip file
                <a href="http://dita-op.pluginbuilder.org/latest" target="_blank">
                    here
                </a>
                or use the nightly builds' update site:
                <a href="http://dita-op.pluginbuilder.org/nightly/updateSite" target="_blank">
                    http://dita-op.pluginbuilder.org/nightly/updateSite
                </a>
            </div>

        </div>

    </div>
<div class="nested1" id="N203CB"><a name="N203CB"><!-- --></a>
        <h2 class="topictitle2">Downloading the sources</h2>

        <div>
            <div class="section">
                <p>
                    To download the sources you can go to the
                    <a href="http://sourceforge.net/project/showfiles.php?group_id=228491&package_id=276725" target="_blank">
                        project's download page
                    </a>
                    and choose the
                    <span class="filepath">
                        org.dita_op_1.0.0.M1-20080618-src.zip
                    </span>
                    zip file which contains both the binaries and the
                    sources.
                </p>

                <p>
                    Or you can download the sources from the SVN source
                    repository. The repository URL is
                    <a href="http://svn.dita-op.org/svnroot/dita-op/" target="_blank">
                        http://svn.dita-op.org/svnroot/dita-op/
                    </a>
                    and is anonymously accessible.
                </p>

                <p>
                    You can refer to this sourceforge page for detailed
                    information about SVN:
                    <a href="http://alexandria.wiki.sourceforge.net/Subversion+-+Version+Control+for+Source+Code" target="_blank">
                        Subversion - Version Control for Source Code.
                    </a>
                </p>

            </div>

        </div>

    </div>
</div>
